create table if not exists users (
    user_id BIGINT generated by default as identity primary key,
    user_name varchar(64),
    user_email varchar(128),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email),
);

create table if not exists items (
    item_id BIGINT generated by default as identity primary key,
    item_name varchar(64),
    item_description varchar,
    item_isAvailable varchar,
    item_owner BIGINT references users(user_id)
);

create table if not exists bookings (
    booking_id BIGINT generated by default as identity primary key,
    booking_start timestamp,
    booking_end timestamp,
    item_id BIGINT references items(item_id),
    user_id bigint references users(user_id),
    booking_status varchar
);

create TABLE IF NOT EXISTS comments (
    id BIGINT generated by default as identity primary key,
    text VARCHAR(1000) NOT NULL,
    item_id BIGINT REFERENCES items (item_id) ON delete CASCADE,
    author_id BIGINT REFERENCES users (user_id) ON delete CASCADE,
    created TIMESTAMP
    );

