create table if not exists users (
    id BIGINT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(64),
    email varchar(128),
    CONSTRAINT UQ_EMAIL UNIQUE (email)
);

create TABLE IF NOT EXISTS requests (
    id BIGINT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR NOT NULL,
    requestor_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
    created TIMESTAMP WITHOUT TIME ZONE
);

create table if not exists items (
    id BIGINT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(64),
    description varchar,
    available varchar,
    owner_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    request_id BIGINT REFERENCES requests(id)
);

create table if not exists bookings (
    id BIGINT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP WITHOUT TIME ZONE,
    end_date TIMESTAMP WITHOUT TIME ZONE,
    item_id BIGINT REFERENCES items(id) ON DELETE CASCADE,
    booker_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    status varchar
);

create TABLE IF NOT EXISTS comments (
    id BIGINT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR(1000) NOT NULL,
    item_id BIGINT REFERENCES items (id) ON DELETE CASCADE,
    author_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
    created TIMESTAMP WITHOUT TIME ZONE
);

